In [4]:
import numpy as np
import pandas as pd

In [6]:

x = np.array([3,5,6,8,10])
y = np.array([9,11,14,15,22])
pd.DataFrame({'x':x,'y':y})

    x   y
0   3   9
1   5  11
2   6  14
3   8  15
4  10  22

In [7]:
w0 = 5
w1 =0.2
yp = w0 +w1*x
loss = sum((yp-y)**2)/len(x)
print(loss)
pd.DataFrame({"x":x,"y":y,"yp":yp})

78.59200000000001

    x   y   yp
0   3   9  5.6
1   5  11  6.0
2   6  14  6.2
3   8  15  6.6
4  10  22  7.0