In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name":["Swapnil","Rahul","Mr. Brown"],
    "age" :[20,23,25],
    "sex": ["male","male","male"]
    
}
    
)
df

        Name  age   sex
0    Swapnil   20  male
1      Rahul   23  male
2  Mr. Brown   25  male

In [3]:
df["Name"]

0      Swapnil
1        Rahul
2    Mr. Brown
Name: Name, dtype: object

series

In [4]:
ages = pd.Series([22,23,26],name = "age")
ages

0    22
1    23
2    26
Name: age, dtype: int64

In [5]:
df1 = pd.Series([10,20,30,40,50])
print(df1)
print(df1[1])

0    10
1    20
2    30
3    40
4    50
dtype: int64
20

In [6]:
df2 = pd.Series([20,21,22,23,24],index=["Tom","bob","charlie","brown","thor"])
print(df2)

Tom        20
bob        21
charlie    22
brown      23
thor       24
dtype: int64

properties of series

In [7]:
a1=pd.Series([1,23,3,56,9,7])
a2 = pd.Series([24,56,89,221,12,90])
print(a1+a2)

0     25
1     79
2     92
3    277
4     21
5     97
dtype: int64

Dataframe

In [8]:
df = pd.DataFrame({
    "Name":["Swapnil","Rahul","Mr. Brown"],
    "age" :[20,23,25],
    "sex": ["male","male","male"]
    
}
    
)
df
print(df, type(df))
print(df.index)

        Name  age   sex
0    Swapnil   20  male
1      Rahul   23  male
2  Mr. Brown   25  male <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)

In [9]:
df4= pd.DataFrame([["adam",34],["tom",56],["thor","55"]],columns=["Name","Age"])
print(df4)

   Name Age
0  adam  34
1   tom  56
2  thor  55

In [10]:
import numpy as np

In [11]:
n = np.array([[1,2,3],[4,5,6]])
print(n)
df5 = pd.DataFrame(n,columns=["a","b","c"])
print(df5)

[[1 2 3]
 [4 5 6]]
   a  b  c
0  1  2  3
1  4  5  6

In [12]:
df = pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [13]:
df.head() # first five rows
df.tail() # last five rows
df.sample()

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [15]:
df.shape

(10, 5)

In [16]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [17]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [18]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

AQI Dataset

In [19]:
df7 =pd.read_csv("globalAirQuality.csv")
df7

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [20]:
df7.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [21]:
#selection the data
df7["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [22]:
df7["city"]

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [23]:
df7[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [24]:
df7

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [25]:
print(df7)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [30]:
# Slecting data

df7["country"]
df7[["city","aqi"]]
df7.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object